### ISSUE TITLE
Error in augment() n_events  must be an integer

### ISSUE THREAD

**Issue by camcaan** [contefranz/msmtools#6] opened 2021-04-20 17:05 UTC
The class of the column in my data (hospAdm_number) is integer but I am still getting this error.

> class(Mocdata$hospAdm_nmber)
[1] "integer"

Error in augment(data = Mocdata, data_key = PatID, n_events = hospAdm_number,  :    n_events must be an integer

**Comment by contefranz** [comment] 2021-04-21 14:29
I cannot replicate the error unless you provide a working minimal. `augment()` does check that `n_events` is an integer. I run the example on my data and everything works as expected.

My suggestions are the following: 
1. Check if `Mocdata` is a `data.table`
2. Check again the class of the variable and in case cast it again to integer.
3. Re-run the example. 

I am not flagging this as a bug yet since I don't have enough elements.

**Comment by camcaan** [comment] 2021-04-24 14:03
Hello Francesco,
Thank you for looking into it. I know it works on the hosp data example. I checked my Mocdata and it gives
> class(Mocdata)[1] "data.table" "data.frame"  . Class as both data frame and data.table. The variable is integer but still giving the same error. This is not my actual data but I was just checking it on. May be when my actual data is ready, it will work then I hope.
I have slight confusion about how to use it when I have a separate state "Institutionalisation".
Any thoughts on this?

Kind Regards,



Kamran Khan


Ph.D. student

Institute of Health Informatics, University College London

twitter: @camcaan

Tel: 02076798178 Ext: 48178

________________________________

**Comment by contefranz** [comment] 2021-04-24 14:39
This is not a place to ask for advice on the modeling approach. This is a place to report eventual bugs or to ask for enhancements of the code. Since you think there is a problem with `augment()`, the only way I have to give support is if you set the necessary conditions for me to replicate the issue. 

So, if you are willing to do so I am happy to have a look. If not, I will close this issue as I cannot replicate it. 
Just to be clear, I am suggesting you share the data here so that I can copy paste it into my machine.

**Comment by camcaan** [comment] 2021-04-24 15:01
Thank you Francesco, We can close this issue.

**Comment by camcaan** [comment] 2021-04-25 03:45
<img width="1291" alt="Screenshot 2021-04-25 at 04 43 07" src="https://user-images.githubusercontent.com/42880915/115979954-e74e5700-a580-11eb-9e4e-e570c888a9be.png">
I tried it on a chunck og my data and it worked fine. However, when I try  the augment() on the whole data it gives this  error.
I hope you can view the attached screenshot.

**Comment by contefranz** [comment] 2021-04-26 07:38
This is a recycling problem which could not be directly related to `augment()`. Again, I cannot replicate this unless you share a reproducible example. I am closing this thread as it seems we are not moving forward.

**Closed as completed by contefranz** 2021-04-26 07:38 UTC
